development: &default
  adapter: postgresql
  encoding: unicode
  database: rails-api-bootstrap_development
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'rails-api-bootstrap') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'rails-api-bootstrap') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>

test: &test
  <<: *default
  database: rails-api-bootstrap_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
