shared:
  jwt_secret_key: test
  default_email_sender: <%= ENV.fetch('DEFAULT_EMAIL_SENDER') { 'no-reply@rails-api-bootstrap.com' } %>
  max_requests_per_second: <%= ENV.fetch('MAX_REQUESTS_PER_SECOND') { 5 } %>

production:
  jwt_secret_key: <%= ENV['JWT_SECRET_KEY'] %>
